Fix default sorting value
prusa3d/Prusa-Link-Web pull request #315
Opened 2022-12-07 09:49 UTC by Lowentwickler

2022-12-08 12:04 UTC, vorner approved these changes
This seems to solve the issue for me :+1:

2022-12-09 09:59 UTC, ondratu requested changes

2022-12-09 09:59 UTC, ondratu commented on src/printer/components/files.js
> +  console.log("Sort", metadata.sort);
no console log please

2022-12-09 13:34 UTC, Lowentwickler commented on src/printer/components/files.js
> +  console.log("Sort", metadata.sort);
Sure

2022-12-09 13:34 UTC, ondratu approved these changes

2022-12-09 13:35 UTC, merged