Fix storage free space indicator
prusa3d/Prusa-Link-Web pull request #367
Opened 2023-03-03 09:16 UTC by Lowentwickler

Before:
![Snímek obrazovky z 2023-03-03 10-15-33](https://user-images.githubusercontent.com/5078803/222680766-ffe3a4f0-cfb0-4648-8eeb-ff00fca5267b.png)

After:
![Snímek obrazovky z 2023-03-03 10-12-25](https://user-images.githubusercontent.com/5078803/222680813-4f407c1f-e6f9-4c86-8fd6-26332d750d99.png)

2023-03-06 13:05 UTC, tomashusakk requested changes
<img width="1097" alt="Screenshot 2023-03-06 at 14 04 57" src="https://user-images.githubusercontent.com/108595413/223118284-e6be1223-5571-4a5d-8b1c-26621c3ef30d.png">

na macu ve všech prohlížečích mám takový skoro nekonečný bar

2023-03-13 09:02 UTC, Lowentwickler commented
Must be OK now

2023-03-14 12:19 UTC, tomashusakk requested changes
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/108595413/224999021-d0c23393-3b47-4aa5-9d39-b1ba85847212.png">
still not ok :(

2023-04-05 10:29 UTC, tomashusakk approved these changes

2023-04-05 12:47 UTC, merged