Integrate status endpoint with job and transfer requests
prusa3d/Prusa-Link-Web pull request #376
Opened 2023-03-20 14:51 UTC by voxelias

To test:

- Print start/stop/pause/resume
- Printer controls
- Printer settings
- File actions
- New: folder removal
- New: folder creation

2023-04-21 11:32 UTC, tomashusakk requested changes
po kliknutí na pause - nejde dát stop - odpoví mi to 409, printer is not printing a zašednou mi tlačítka poté (což je správně v tu chvíli kdy příkaz funguje)

pokud dám stop hned na začátku tisku během nahřívání (tiskárna čeká až se donahřeje než se stopne) - nejde dát download - 404 not found

2023-04-25 09:16 UTC, Lowentwickler commented
Tlačítka jsem opravil. Download by měl fungovat. Zkontroluj že máš poslední BE. Připadně pošli screenshot z devtools, jak dopadl ten požadavek na stažení, hlavičky atd.

2023-04-26 13:14 UTC, Lowentwickler commented
![Snímek obrazovky z 2023-04-26 15-12-20](https://user-images.githubusercontent.com/5078803/234585833-a21d6122-57b4-4c85-b1df-787e17484ac2.png)
![Snímek obrazovky z 2023-04-26 15-12-15](https://user-images.githubusercontent.com/5078803/234585838-7accc81a-cf24-4d5b-874e-7c1db0d9a79c.png)

Takhle by to teď mělo vypadat. 

Tlačítka se už neblokujou, jestli z BE se vrací chyba.

2023-05-02 10:57 UTC, tomashusakk approved these changes

2023-05-02 11:36 UTC, merged